### ISSUE TITLE
About Copy action

### ISSUE THREAD

**Issue by dlqudwns** [ConfeitoHS/arcle#2]
When source is "I", Copy() action results in an error when the bbox of selection is larger than the input grid.

e.g., when H=W=30 (fully selected action) and cls.input_.shape=(5,7)

`np.copyto(cls.clip[:H, :W], cls.input_[xmin:xmin+H, ymin:ymin+W], where=np.logical_and(cls.input_[xmin:xmin+H, ymin:ymin+W]>0,sel[xmin:xmin+H, ymin:ymin+W] ))`

(line 288 of arcle.action.object)

results in

`ValueError: operands could not be broadcast together with shapes (5,7) (30,30) `

**Comment by ConfeitoHS** [comment]
I am terribly sorry for the late answer. In 81ee019159ee1571a0937bdc33265998dc90ecf3, this bug is fixed.
Currently developing branch will be released as 0.2.5 soon.
