### ISSUE TITLE
Possible bugs on o2arcenv actions

### ISSUE THREAD

**Issue by dlqudwns** [ConfeitoHS/arcle#3]
Lines

https://github.com/ConfeitoHS/arcle/blob/f9f38b38b78cf20522970225c2dbdf81e9ff4239/arcle/actions/object.py#L137

https://github.com/ConfeitoHS/arcle/blob/f9f38b38b78cf20522970225c2dbdf81e9ff4239/arcle/actions/object.py#L164

should be:
`p = p[ stx-x : edx-x, sty-y : edy-y]`

otherwise it may result in an error in some cases, e.g. x = -1, h = 5, gh = 4

Furthermore:

https://github.com/ConfeitoHS/arcle/blob/f9f38b38b78cf20522970225c2dbdf81e9ff4239/arcle/actions/object.py#L301

seems to be not consistent: shouldn't this be xmax > ss_h as well (consistent to ymax > ss_w)?

**Comment by ConfeitoHS** [comment]
Thank you for your notice, and both are definitely mistakes.
I amended both possible bug to the recent commit, with 0.2.5.post1 post release.
